services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/al2023/Dockerfile
      args:
        - USERNAME=${USERNAME:-appuser}
        - GROUPNAME=${GROUPNAME:-appuser}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - ARCH=${ARCH:-x86_64}
        - PYTHON_VERSION=${PYTHON_VERSION:-3.12.0}
        - DOCKER_COMPOSE_VERSION=${DOCKER_COMPOSE_VERSION:-2.32.4}
        - HOST_DOCKER_GID=${HOST_DOCKER_GID:-1001}
    volumes:
      - /run/docker.sock:/run/docker.sock
    tty: true